# Generated by Django 4.2.14 on 2025-02-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_created", models.DateTimeField(auto_now_add=True)),
                ("_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "In Progress"), (2, "Completed")], default=1
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(default="")),
                ("due_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "task",
                "managed": True,
            },
        ),
    ]
